services:
  # Postgres Database service
  db:
    image: postgres:15-alpine
    restart: always
    shm_size: 128mb
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adminpassword
      POSTGRES_DB: RetinaCare_DB
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # GUI helper for postgres database
  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - db

  # Backend service
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.backend
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://admin:adminpassword@db:5432/RetinaCare_DB
    depends_on:
      - db
    volumes:
      - ./backend:/app

volumes:
  postgres_data: